# Generated by Django 2.1.7 on 2019-02-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(default='osgkr', editable=False, max_length=100, unique=True),
        ),
    ]
