# Generated by Django 2.1.7 on 2019-02-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190214_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(default='zwshy', editable=False, max_length=100, unique=True),
        ),
    ]
