# Generated by Django 2.1.7 on 2019-02-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190214_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(default='bhfvx', editable=False, max_length=100, unique=True),
        ),
    ]
