# Generated by Django 2.1.7 on 2019-02-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190214_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(default='erkzj', editable=False, max_length=100, unique=True),
        ),
    ]
